"""trying the game table

Revision ID: 40a051f844a4
Revises: 5aff152f765d
Create Date: 2024-07-12 19:23:18.370777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a051f844a4'
down_revision = '5aff152f765d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('player_hand', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('computer_hand', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('tablecard', sa.String(), nullable=False))
        batch_op.drop_column('knight_y')
        batch_op.drop_column('board')
        batch_op.drop_column('rook_y')
        batch_op.drop_column('rook_x')
        batch_op.drop_column('knight_x')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knight_x', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rook_x', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rook_y', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('board', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('knight_y', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('tablecard')
        batch_op.drop_column('computer_hand')
        batch_op.drop_column('player_hand')
        batch_op.drop_column('deck')

    # ### end Alembic commands ###
