"""finished authentication

Revision ID: 5aff152f765d
Revises: 
Create Date: 2024-07-12 03:05:32.842479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aff152f765d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('board', sa.Text(), nullable=False),
    sa.Column('knight_x', sa.Integer(), nullable=False),
    sa.Column('knight_y', sa.Integer(), nullable=False),
    sa.Column('rook_x', sa.Integer(), nullable=False),
    sa.Column('rook_y', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('member')
    # ### end Alembic commands ###
